services:
  collections-dlp-webui:
    build: .
    container_name: collections-dlp-webui
    restart: unless-stopped
    ports:
      - "5555:5555"
    volumes:
      - ${DOWNLOADS_PATH:-./downloads}:/app/downloads
      - ${CONFIGS_PATH:-collections-dlp-webui}:/app/config
      - ${COLLECTIONS_PATH:-collections-dlp-webui}:/app/collections
      - ${COOKIES_PATH:-collections-dlp-webui}:/app/cookies

volumes:
  collections-dlp-webui: