services:
  collections-dlp-webui:
    build: .
    container_name: collections-dlp-webui
    ports:
      - "5555:5555"
    volumes:
      - ${DOWNLOADS_PATH}:/app/downloads
      - ${CONFIG_PATH}:/app/config/config.json
    restart: unless-stopped
